# We'll never use this.
# This is our guide template to implement task_executor.py
---
apiVersion: batch/v1
kind: Job
metadata:
  name: my-job-id
  namespace: jobdemonamespace
  labels:
    job_name: my-job-id
spec:
  template:
    metadata:
      labels:
        app: my-job-pod-id
      name: my-job-pod-id
    spec:
      containers:
        - image: "shuffler:latest"
          imagePullPolicy: Never
          name: "shuffler"
          command:
            - python3
            - -u
            - ./shuffler.py
          args:
            - "Kubernetes"
      restartPolicy: Never